### PR TITLE
[WIP] Update AHS notebooks to use AHS utility functions from the SDK

### PR DESCRIPTION
**Pull request by maolinml**
*Issue #, if available:*

Resolving [this issue](https://github.com/aws/amazon-braket-examples/issues/270) by updating the AHS notebook to use AHS utility functions from the SDK.

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by krneta** [comment]
Do we know why the RMS doubled in the local sim example?

**Comment by guomanmin** [comment]
Chatted with @maolinml (who can confirm) that we're looking at a merge ETA of Sept 26

**Comment by maolinml** [comment]
> Do we know why the RMS doubled in the local sim example?

Sorry for not replying earlier. I tried running the same cell several times, and the RMS vary from 0.18 to 0.3. I then increase the number of shots from 1000 to 10000, and the RMS stabilizes to around 0.22. I repeat this for both `drive = DrivingField.from_lists(...)` and `drive=get_drive(...)` (the original code) and the RMS stabilizes to the roughly the same value. Thus, let's keep this value.

**Comment by guomanmin** [comment]
When squash and merge, please use "fix" or "feature" to allow the commit message for this PR to follow [conventional commit ](https://gist.github.com/qoomon/5dfcdf8eec66a051ecd85625518cfd13) style (see other commits in the repo)

**Review by guomanmin — DISMISSED** [review]

**Comment by krneta** [comment]
> > Do we know why the RMS doubled in the local sim example?
> 
> Sorry for not replying earlier. I tried running the same cell several times, and the RMS vary from 0.18 to 0.3. I then increase the number of shots from 1000 to 10000, and the RMS stabilizes to around 0.22. I repeat this for both `drive = DrivingField.from_lists(...)` and `drive=get_drive(...)` (the original code) and the RMS stabilizes to the roughly the same value. Thus, let's keep this value.

Does changing it to 10000 impact the test run time?

**Comment by maolin2** [comment]
> > > Do we know why the RMS doubled in the local sim example?
> > 
> > 
> > Sorry for not replying earlier. I tried running the same cell several times, and the RMS vary from 0.18 to 0.3. I then increase the number of shots from 1000 to 10000, and the RMS stabilizes to around 0.22. I repeat this for both `drive = DrivingField.from_lists(...)` and `drive=get_drive(...)` (the original code) and the RMS stabilizes to the roughly the same value. Thus, let's keep this value.
> 
> Does changing it to 10000 impact the test run time?

No. The simulation itself takes most of the runtime, and since we perform the sampling at the end of the simulation, sampling 1000 shots and 10000 shots do not have much difference, in terms of runtime. This is also evident if we compare the runtime before and after this PR, and we can see that the runtimes are roughly the same order.

**Review by krneta — APPROVED** [review]

**Comment by krneta** [comment]
When are we planning on removing the legacy functions from the utils file?

**Comment by maolin2** [comment]
> Do we need to remove the legacy functions from the utils file?

Good question. I was thinking to keep the functions in case some customers are still using them or prefer to use them. What is the best practice in this case?

**Comment by krneta** [comment]
> > Do we need to remove the legacy functions from the utils file?
> 
> Good question. I was thinking to keep the functions in case some customers are still using them or prefer to use them. What is the best practice in this case?

I think we should remove them. The files in the examples repo are often changed without a view into backward compatibility and are not a supported part of the BDK. The customers that are using the legacy functions can move to the new functions, especially because they need to start a new container before the file is updated anyway (in which case they would lose some functionality anyway). However, that's just my opinion.

**Comment by maolinml** [comment]
> > > Do we need to remove the legacy functions from the utils file?
> > 
> > 
> > Good question. I was thinking to keep the functions in case some customers are still using them or prefer to use them. What is the best practice in this case?
> 
> I think we should remove them. The files in the examples repo are often changed without a view into backward compatibility and are not a supported part of the BDK. The customers that are using the legacy functions can move to the new functions, especially because they need to start a new container before the file is updated anyway (in which case they would lose some functionality anyway). However, that's just my opinion.

If we changed examples repo without a view into backward compatibility, then it makes sense to remove the legacy functions, and I have done that. Could you check why the "Build Conda Environment" failed?

**Review by krneta — APPROVED** [review]

**Pull request merged**
